### ISSUE TITLE
gocheckcov check init -p coverage.out strange result

### ISSUE THREAD

**Issue by marcelloh** [cvgw/gocheckcov#1]
2019/12/11 10:22:23 could not retrieve node from filepath open /Users/marcelloh/go/src/Users/marcelloh/data/go-business/impact_generated/main.go: no such file or directory

I still see here the Go path before the modules path

**Comment by cvgw** [comment]
@marcelloh looks like I made a silly mistake and forgot to merge those changes. Can you give https://github.com/cvgw/gocheckcov/pull/2 a try and see if that resolves your issue?

**Comment by cvgw** [comment]
This should be fixed as of master @https://github.com/cvgw/gocheckcov/commit/cc20daf656ea93b42310706527317e34e4e38f0e

**Comment by marcelloh** [comment]
You're the best ! It works super.
So what I do in my makefile:
```
@GOPATH=$(GOPATH) GOBIN=$(GOBIN) gotest -count=1 -timeout 30s -coverprofile coverage.out ./...
@gocheckcov check --minimum-coverage 80 --profile-file coverage.out --print-src
```
